@HostAddress = https://localhost:7105

### The table of contents: one summary per timeline folder found under TIMELINES_ROOT_PATH.
GET {{HostAddress}}/v1/timelines
Accept: application/json

###

@TimelineId = 01979e65-0ab5-7a48-85d5-968f1be9f671

### One timeline, whole.
GET {{HostAddress}}/v1/timelines/{{TimelineId}}
Accept: application/json

###

### What is actually in that timeline's images/ folder.
GET {{HostAddress}}/v1/timelines/{{TimelineId}}/images
Accept: application/json

###

### And its narratives/ folder.
GET {{HostAddress}}/v1/timelines/{{TimelineId}}/narratives
Accept: application/json

###

GET {{HostAddress}}/v1/timelines/{{TimelineId}}/categories
Accept: application/json
