import {
  Accessibility,
  Activity,
  AlarmSmoke,
  Ambulance,
  Anchor,
  Apple,
  Archive,
  Atom,
  Award,
  Axe,
  Baby,
  Backpack,
  Banana,
  Bandage,
  Banknote,
  Bed,
  BedDouble,
  Beer,
  Bell,
  Bike,
  Bird,
  Bone,
  Book,
  BookOpen,
  Bookmark,
  BoomBox,
  BottleWine,
  Box,
  Brain,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseMedical,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  BusFront,
  CableCar,
  Cake,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  CarFront,
  CarTaxiFront,
  Caravan,
  Carrot,
  Castle,
  Cat,
  ChefHat,
  Cherry,
  Church,
  Circle,
  Clapperboard,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CloudSun,
  Cloudy,
  Code,
  Coffee,
  Coins,
  Compass,
  Construction,
  Contact,
  ContactRound,
  CookingPot,
  CreditCard,
  Croissant,
  Cross,
  Crown,
  CupSoda,
  Dna,
  Dog,
  DollarSign,
  Donut,
  DoorOpen,
  Drill,
  Droplet,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  Earth,
  Egg,
  Euro,
  Eye,
  Factory,
  Feather,
  Fence,
  FileText,
  Film,
  Fish,
  FishingRod,
  Flag,
  Flame,
  Flashlight,
  FlaskConical,
  Flower,
  Flower2,
  Folder,
  Footprints,
  ForkKnifeCrossed,
  Forklift,
  Frown,
  Fuel,
  Gamepad,
  Gamepad2,
  Gem,
  Gift,
  GlassWater,
  Glasses,
  Globe,
  Goal,
  GraduationCap,
  Guitar,
  Ham,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  HandHelping,
  Handbag,
  Handshake,
  HatGlasses,
  Haze,
  Headphones,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  History,
  Hospital,
  Hourglass,
  House,
  HousePlug,
  IceCream,
  IceCream2,
  IceCreamCone,
  IdCard,
  IdCardLanyard,
  Key,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Laptop2,
  Leaf,
  LeafyGreen,
  Library,
  Lightbulb,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
  Luggage,
  Mail,
  MailOpen,
  Mailbox,
  Map,
  MapPin,
  MapPinned,
  Mars,
  Martini,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  Monitor,
  Moon,
  Motorbike,
  Mountain,
  MountainSnow,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Navigation2,
  Notebook,
  Origami,
  Package,
  Package2,
  Paintbrush,
  Palette,
  Palmtree,
  Panda,
  ParkingMeter,
  PawPrint,
  Pen,
  PenLine,
  Pencil,
  PencilLine,
  PersonStanding,
  PhilippinePeso,
  Phone,
  Piano,
  Pickaxe,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plane,
  PlayingCard,
  PlayingCards,
  PlayingCardsFan,
  Plug,
  Plug2,
  Popcorn,
  PoundSterling,
  Presentation,
  Printer,
  Puzzle,
  Rabbit,
  Radio,
  Rainbow,
  Rat,
  Receipt,
  Refrigerator,
  Ribbon,
  Road,
  Rocket,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  School,
  Scissors,
  Shell,
  Shield,
  Ship,
  ShipWheel,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  Shrimp,
  Signpost,
  Smartphone,
  Smile,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Sprout,
  Squirrel,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Sword,
  Swords,
  Syringe,
  Tag,
  Target,
  Tent,
  Theater,
  Thermometer,
  Ticket,
  Timer,
  Toolbox,
  Tornado,
  Tractor,
  Train,
  TrainFront,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Tv2,
  Umbrella,
  University,
  User,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  Vault,
  Vegan,
  Venus,
  Volleyball,
  Wallet,
  Wallet2,
  Warehouse,
  Waves,
  Wheat,
  Wind,
  Wine,
  Worm,
  Wrench,
  Zap
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/**
 * The icons offered for categories.
 *
 * Lucide ships over 2,000 distinct icons (6,000+ exports, three aliases each). Importing
 * them all would defeat tree-shaking and bundle the lot, so this is a curated set named
 * explicitly — chosen by filtering out interface chrome (arrows, chart types, text
 * formatting), then modifier variants of the same object ("alarm-clock-minus"), then
 * keeping what a life actually contains: places, people, work, study, health, food,
 * animals, nature, travel, leisure, money, tools and time.
 *
 * Adding one is a single line here. The stored value is Lucide's own kebab-case name, so
 * widening the list never requires touching stored data.
 */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  'accessibility': Accessibility,
  'activity': Activity,
  'alarm-smoke': AlarmSmoke,
  'ambulance': Ambulance,
  'anchor': Anchor,
  'apple': Apple,
  'archive': Archive,
  'atom': Atom,
  'award': Award,
  'axe': Axe,
  'baby': Baby,
  'backpack': Backpack,
  'banana': Banana,
  'bandage': Bandage,
  'banknote': Banknote,
  'bed': Bed,
  'bed-double': BedDouble,
  'beer': Beer,
  'bell': Bell,
  'bike': Bike,
  'bird': Bird,
  'bone': Bone,
  'book': Book,
  'book-open': BookOpen,
  'bookmark': Bookmark,
  'boom-box': BoomBox,
  'bottle-wine': BottleWine,
  'box': Box,
  'brain': Brain,
  'briefcase': Briefcase,
  'briefcase-business': BriefcaseBusiness,
  'briefcase-medical': BriefcaseMedical,
  'brush': Brush,
  'bug': Bug,
  'building': Building,
  'building-2': Building2,
  'bus': Bus,
  'bus-front': BusFront,
  'cable-car': CableCar,
  'cake': Cake,
  'calculator': Calculator,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'camera': Camera,
  'car': Car,
  'car-front': CarFront,
  'car-taxi-front': CarTaxiFront,
  'caravan': Caravan,
  'carrot': Carrot,
  'castle': Castle,
  'cat': Cat,
  'chef-hat': ChefHat,
  'cherry': Cherry,
  'church': Church,
  'circle': Circle,
  'clapperboard': Clapperboard,
  'clipboard': Clipboard,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'cloud': Cloud,
  'cloud-drizzle': CloudDrizzle,
  'cloud-lightning': CloudLightning,
  'cloud-moon': CloudMoon,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'cloud-sun': CloudSun,
  'cloudy': Cloudy,
  'code': Code,
  'coffee': Coffee,
  'coins': Coins,
  'compass': Compass,
  'construction': Construction,
  'contact': Contact,
  'contact-round': ContactRound,
  'cooking-pot': CookingPot,
  'credit-card': CreditCard,
  'croissant': Croissant,
  'cross': Cross,
  'crown': Crown,
  'cup-soda': CupSoda,
  'dna': Dna,
  'dog': Dog,
  'dollar-sign': DollarSign,
  'donut': Donut,
  'door-open': DoorOpen,
  'drill': Drill,
  'droplet': Droplet,
  'drum': Drum,
  'drumstick': Drumstick,
  'dumbbell': Dumbbell,
  'ear': Ear,
  'earth': Earth,
  'egg': Egg,
  'euro': Euro,
  'eye': Eye,
  'factory': Factory,
  'feather': Feather,
  'fence': Fence,
  'file-text': FileText,
  'film': Film,
  'fish': Fish,
  'fishing-rod': FishingRod,
  'flag': Flag,
  'flame': Flame,
  'flashlight': Flashlight,
  'flask-conical': FlaskConical,
  'flower': Flower,
  'flower-2': Flower2,
  'folder': Folder,
  'footprints': Footprints,
  'fork-knife-crossed': ForkKnifeCrossed,
  'forklift': Forklift,
  'frown': Frown,
  'fuel': Fuel,
  'gamepad': Gamepad,
  'gamepad-2': Gamepad2,
  'gem': Gem,
  'gift': Gift,
  'glass-water': GlassWater,
  'glasses': Glasses,
  'globe': Globe,
  'goal': Goal,
  'graduation-cap': GraduationCap,
  'guitar': Guitar,
  'ham': Ham,
  'hammer': Hammer,
  'hand': Hand,
  'hand-coins': HandCoins,
  'hand-heart': HandHeart,
  'hand-helping': HandHelping,
  'handbag': Handbag,
  'handshake': Handshake,
  'hat-glasses': HatGlasses,
  'haze': Haze,
  'headphones': Headphones,
  'heart': Heart,
  'heart-crack': HeartCrack,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  'history': History,
  'hospital': Hospital,
  'hourglass': Hourglass,
  'house': House,
  'house-plug': HousePlug,
  'ice-cream': IceCream,
  'ice-cream-2': IceCream2,
  'ice-cream-cone': IceCreamCone,
  'id-card': IdCard,
  'id-card-lanyard': IdCardLanyard,
  'key': Key,
  'key-round': KeyRound,
  'lamp': Lamp,
  'landmark': Landmark,
  'laptop': Laptop,
  'laptop-2': Laptop2,
  'leaf': Leaf,
  'leafy-green': LeafyGreen,
  'library': Library,
  'lightbulb': Lightbulb,
  'lock': Lock,
  'lock-keyhole': LockKeyhole,
  'lock-keyhole-open': LockKeyholeOpen,
  'lock-open': LockOpen,
  'luggage': Luggage,
  'mail': Mail,
  'mail-open': MailOpen,
  'mailbox': Mailbox,
  'map': Map,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  'mars': Mars,
  'martini': Martini,
  'medal': Medal,
  'megaphone': Megaphone,
  'message-circle': MessageCircle,
  'mic': Mic,
  'microscope': Microscope,
  'microwave': Microwave,
  'milestone': Milestone,
  'milk': Milk,
  'monitor': Monitor,
  'moon': Moon,
  'motorbike': Motorbike,
  'mountain': Mountain,
  'mountain-snow': MountainSnow,
  'music': Music,
  'music-2': Music2,
  'music-3': Music3,
  'music-4': Music4,
  'navigation': Navigation,
  'navigation-2': Navigation2,
  'notebook': Notebook,
  'origami': Origami,
  'package': Package,
  'package-2': Package2,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'palmtree': Palmtree,
  'panda': Panda,
  'parking-meter': ParkingMeter,
  'paw-print': PawPrint,
  'pen': Pen,
  'pen-line': PenLine,
  'pencil': Pencil,
  'pencil-line': PencilLine,
  'person-standing': PersonStanding,
  'philippine-peso': PhilippinePeso,
  'phone': Phone,
  'piano': Piano,
  'pickaxe': Pickaxe,
  'piggy-bank': PiggyBank,
  'pill': Pill,
  'pin': Pin,
  'pizza': Pizza,
  'plane': Plane,
  'playing-card': PlayingCard,
  'playing-cards': PlayingCards,
  'playing-cards-fan': PlayingCardsFan,
  'plug': Plug,
  'plug-2': Plug2,
  'popcorn': Popcorn,
  'pound-sterling': PoundSterling,
  'presentation': Presentation,
  'printer': Printer,
  'puzzle': Puzzle,
  'rabbit': Rabbit,
  'radio': Radio,
  'rainbow': Rainbow,
  'rat': Rat,
  'receipt': Receipt,
  'refrigerator': Refrigerator,
  'ribbon': Ribbon,
  'road': Road,
  'rocket': Rocket,
  'ruler': Ruler,
  'sailboat': Sailboat,
  'salad': Salad,
  'sandwich': Sandwich,
  'school': School,
  'scissors': Scissors,
  'shell': Shell,
  'shield': Shield,
  'ship': Ship,
  'ship-wheel': ShipWheel,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  'shovel': Shovel,
  'shrimp': Shrimp,
  'signpost': Signpost,
  'smartphone': Smartphone,
  'smile': Smile,
  'snail': Snail,
  'snowflake': Snowflake,
  'sofa': Sofa,
  'soup': Soup,
  'sparkles': Sparkles,
  'sprout': Sprout,
  'squirrel': Squirrel,
  'stamp': Stamp,
  'star': Star,
  'stethoscope': Stethoscope,
  'store': Store,
  'sun': Sun,
  'sunrise': Sunrise,
  'sunset': Sunset,
  'sword': Sword,
  'swords': Swords,
  'syringe': Syringe,
  'tag': Tag,
  'target': Target,
  'tent': Tent,
  'theater': Theater,
  'thermometer': Thermometer,
  'ticket': Ticket,
  'timer': Timer,
  'toolbox': Toolbox,
  'tornado': Tornado,
  'tractor': Tractor,
  'train': Train,
  'train-front': TrainFront,
  'trash': Trash,
  'trash-2': Trash2,
  'tree-deciduous': TreeDeciduous,
  'tree-pine': TreePine,
  'trophy': Trophy,
  'truck': Truck,
  'turtle': Turtle,
  'tv': Tv,
  'tv-2': Tv2,
  'umbrella': Umbrella,
  'university': University,
  'user': User,
  'user-round': UserRound,
  'users': Users,
  'users-round': UsersRound,
  'utensils': Utensils,
  'vault': Vault,
  'vegan': Vegan,
  'venus': Venus,
  'volleyball': Volleyball,
  'wallet': Wallet,
  'wallet-2': Wallet2,
  'warehouse': Warehouse,
  'waves': Waves,
  'wheat': Wheat,
  'wind': Wind,
  'wine': Wine,
  'worm': Worm,
  'wrench': Wrench,
  'zap': Zap,
};

export const ICON_NAMES = Object.keys(CATEGORY_ICONS);

/** Null for an unset icon, or a name this build does not carry. */
export function iconFor(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return CATEGORY_ICONS[name] ?? null;
}
